import Foundation
import Testing
@testable import TraceMacAppUI

@Suite("TraceDirectoryWatcher Tests")
struct TraceDirectoryWatcherTests {
  private let tempDirectory: URL

  init() throws {
    tempDirectory = FileManager.default.temporaryDirectory
      .appendingPathComponent("TraceDirectoryWatcherTests-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true)
  }

  private func cleanup() {
    try? FileManager.default.removeItem(at: tempDirectory)
  }

  @Test("Watcher can start and stop without errors")
  func startAndStopSucceeds() throws {
    defer { cleanup() }
    let watcher = TraceDirectoryWatcher(directoryURL: tempDirectory) {}
    try watcher.start()
    watcher.stop()
  }

  @Test("Writing a file triggers the onChange callback")
  @MainActor
  func writingFileTriggerCallback() async throws {
    defer { cleanup() }
    try await confirmation(expectedCount: 1) { confirmed in
      // Use a debounce window long enough to coalesce the multiple FSEvents
      // generated by an atomic write (temp file creation + rename).
      let watcher = TraceDirectoryWatcher(directoryURL: tempDirectory, debounceMilliseconds: 100) {
        confirmed()
      }
      try watcher.start()

      let fileURL = tempDirectory.appendingPathComponent("trigger.txt", isDirectory: false)
      try Data("hello".utf8).write(to: fileURL, options: .atomic)

      // Wait for debounce window + kernel FS event delivery + dispatch.
      try await Task.sleep(for: .milliseconds(500))
      watcher.stop()
    }
  }

  @Test("Starting when already started is a no-op")
  func doubleStartIsNoOp() throws {
    defer { cleanup() }
    let watcher = TraceDirectoryWatcher(directoryURL: tempDirectory) {}
    try watcher.start()
    // Second start should not throw or create a duplicate source.
    try watcher.start()
    watcher.stop()
  }

  @Test("Stop cleans up resources")
  func stopCleansUpResources() throws {
    defer { cleanup() }
    let watcher = TraceDirectoryWatcher(directoryURL: tempDirectory) {}
    try watcher.start()
    watcher.stop()
    // Stopping again should be safe (idempotent).
    watcher.stop()
  }
}
